codecov:
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  # green range
  range: "80...100"

  status:
    project:
      default:
        target: auto
        threshold: 2%
        if_ci_failed: success #success, failure, error, ignore
        only_pulls: false

    patch:
      default:
        target: 90%
        threshold: 0%
        if_ci_failed: success #success, failure, error, ignore
        only_pulls: false

ignore:
  - "lib/metalink/seeds"
  - "lib/metalink/scripts"
